package ui;

import cardamom.Image;
import core.Manager;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import ui.listeners.PictureListener;

/**
 *
 * @author Ondřej Bleha
 */
public class Gui extends javax.swing.JFrame {
    private final Image image;
    private final Manager manager;
    
    public Gui(Image image) {
        this.image = image;
        manager = new Manager(this.image);
        
        initComponents();
        
        picture.addActionListener(new PictureListener(image, picture));
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picturePane = new javax.swing.JPanel();
        picture = new javax.swing.JButton();
        push = new javax.swing.JButton();
        pull = new javax.swing.JButton();
        save = new javax.swing.JButton();
        flush = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        menu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cardamom");
        setFocusable(false);
        setName("frame"); // NOI18N
        setResizable(false);

        picture.setText("Načíst obrázek");
        picture.setPreferredSize(new java.awt.Dimension(207, 50));

        push.setText("vložit");
        push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushActionPerformed(evt);
            }
        });

        pull.setText("vytáhnout");
        pull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pullActionPerformed(evt);
            }
        });

        save.setText("uložit");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        flush.setText("zavřít");

        javax.swing.GroupLayout picturePaneLayout = new javax.swing.GroupLayout(picturePane);
        picturePane.setLayout(picturePaneLayout);
        picturePaneLayout.setHorizontalGroup(
            picturePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(picturePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(picturePaneLayout.createSequentialGroup()
                        .addComponent(push)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pull)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flush)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        picturePaneLayout.setVerticalGroup(
            picturePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(picturePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(push)
                    .addComponent(pull)
                    .addComponent(save)
                    .addComponent(flush))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(text);

        fileMenu.setText("Soubor");
        menu.add(fileMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(picturePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(picturePane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushActionPerformed
        manager.pushText(text.getText());
    }//GEN-LAST:event_pushActionPerformed

    private void pullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pullActionPerformed
        text.setText(manager.pullText());
    }//GEN-LAST:event_pullActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        JFileChooser fc = new JFileChooser("~");
         FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG & GIF Images", "jpg", "gif");
        fc.setFileFilter(filter);
        int vysledek = fc.showOpenDialog(this);
        if (vysledek == JFileChooser.APPROVE_OPTION) {
            image.saveImage(fc.getSelectedFile());
        }
    }//GEN-LAST:event_saveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton flush;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JButton picture;
    private javax.swing.JPanel picturePane;
    private javax.swing.JButton pull;
    private javax.swing.JButton push;
    private javax.swing.JButton save;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables
}
